[package]
name = "dag"
version = "0.1.0"
edition = "2018"

[dependencies]
indexedlog = { path = "../indexedlog" }
minibytes = { path = "../minibytes" }
vlqencoding = { path = "../vlqencoding" }

anyhow = "1.0.20"
bitflags = "1"
byteorder = "1.2.7"
fs2 = "0.4.3"
indexmap = "1.0.1"
serde = { version = "1", features = ["derive"] }
tempfile = "3.0.7"

[dev-dependencies]
bindag = { path = "bindag" }
drawdag = { path = "../drawdag" }
minibench = { path = "../minibench" }
quickcheck = "0.9"

[[bench]]
name = "spanset"
harness = false

[[bench]]
name = "segment_sizes"
harness = false

[[bench]]
name = "dag_ops"
harness = false
