name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run dag tests
      run: cargo test --target-dir target --manifest-path dag/Cargo.toml --lib
    - name: Run drawdag tests
      run: cargo test --target-dir target --manifest-path drawdag/Cargo.toml --lib
    - name: Run gitdag tests
      run: cargo test --target-dir target --manifest-path gitdag/Cargo.toml --lib
    - name: Run indexedlog tests
      run: cargo test --target-dir target --manifest-path indexedlog/Cargo.toml --lib
    - name: Run mincode tests
      run: cargo test --target-dir target --manifest-path mincode/Cargo.toml --lib
    - name: Run minibytes tests
      run: cargo test --target-dir target --manifest-path minibytes/Cargo.toml --lib --
    - name: Run vlqencoding tests
      run: cargo test --target-dir target --manifest-path vlqencoding/Cargo.toml --lib --
